// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub.proto

package hub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConnectionErr int32

const (
	ConnectionErr_OK            ConnectionErr = 0
	ConnectionErr_EOF           ConnectionErr = 1
	ConnectionErr_UNEXPECTEDEOF ConnectionErr = 2
	ConnectionErr_SHORTWRITE    ConnectionErr = 3
	ConnectionErr_CLOSEDPIPE    ConnectionErr = 4
)

var ConnectionErr_name = map[int32]string{
	0: "OK",
	1: "EOF",
	2: "UNEXPECTEDEOF",
	3: "SHORTWRITE",
	4: "CLOSEDPIPE",
}
var ConnectionErr_value = map[string]int32{
	"OK":            0,
	"EOF":           1,
	"UNEXPECTEDEOF": 2,
	"SHORTWRITE":    3,
	"CLOSEDPIPE":    4,
}

func (x ConnectionErr) String() string {
	return proto.EnumName(ConnectionErr_name, int32(x))
}
func (ConnectionErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hub_8be8b914c2a60943, []int{0}
}

type RegisterRequest struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_8be8b914c2a60943, []int{0}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

type RegisterResponse struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	SessionId            string   `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_8be8b914c2a60943, []int{1}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *RegisterResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type ReadRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_8be8b914c2a60943, []int{2}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (dst *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(dst, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ReadRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReadResponse struct {
	Size                 uint32        `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Data                 []byte        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Err                  ConnectionErr `protobuf:"varint,3,opt,name=err,proto3,enum=hub.ConnectionErr" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_8be8b914c2a60943, []int{3}
}
func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (dst *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(dst, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ReadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ReadResponse) GetErr() ConnectionErr {
	if m != nil {
		return m.Err
	}
	return ConnectionErr_OK
}

type WriteRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_8be8b914c2a60943, []int{4}
}
func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (dst *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(dst, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *WriteRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WriteResponse struct {
	Size                 uint32        `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Err                  ConnectionErr `protobuf:"varint,2,opt,name=err,proto3,enum=hub.ConnectionErr" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_8be8b914c2a60943, []int{5}
}
func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (dst *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(dst, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *WriteResponse) GetErr() ConnectionErr {
	if m != nil {
		return m.Err
	}
	return ConnectionErr_OK
}

type Addr struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	String_              string   `protobuf:"bytes,2,opt,name=string,proto3" json:"string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addr) Reset()         { *m = Addr{} }
func (m *Addr) String() string { return proto.CompactTextString(m) }
func (*Addr) ProtoMessage()    {}
func (*Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_8be8b914c2a60943, []int{6}
}
func (m *Addr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addr.Unmarshal(m, b)
}
func (m *Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addr.Marshal(b, m, deterministic)
}
func (dst *Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addr.Merge(dst, src)
}
func (m *Addr) XXX_Size() int {
	return xxx_messageInfo_Addr.Size(m)
}
func (m *Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_Addr.DiscardUnknown(m)
}

var xxx_messageInfo_Addr proto.InternalMessageInfo

func (m *Addr) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Addr) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "hub.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "hub.RegisterResponse")
	proto.RegisterType((*ReadRequest)(nil), "hub.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "hub.ReadResponse")
	proto.RegisterType((*WriteRequest)(nil), "hub.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "hub.WriteResponse")
	proto.RegisterType((*Addr)(nil), "hub.Addr")
	proto.RegisterEnum("hub.ConnectionErr", ConnectionErr_name, ConnectionErr_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectionClient is the client API for Connection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Write(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Close(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type connectionClient struct {
	cc *grpc.ClientConn
}

func NewConnectionClient(cc *grpc.ClientConn) ConnectionClient {
	return &connectionClient{cc}
}

func (c *connectionClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/hub.Connection/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/hub.Connection/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Write(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/hub.Connection/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Close(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/hub.Connection/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServer is the server API for Connection service.
type ConnectionServer interface {
	Register(context.Context, *RegisterRequest) (*ReadResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Write(context.Context, *ReadRequest) (*ReadResponse, error)
	Close(context.Context, *ReadRequest) (*ReadResponse, error)
}

func RegisterConnectionServer(s *grpc.Server, srv ConnectionServer) {
	s.RegisterService(&_Connection_serviceDesc, srv)
}

func _Connection_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Connection/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Connection/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Connection/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Write(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Connection/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Close(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Connection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hub.Connection",
	HandlerType: (*ConnectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Connection_Register_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Connection_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Connection_Write_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Connection_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub.proto",
}

func init() { proto.RegisterFile("hub.proto", fileDescriptor_hub_8be8b914c2a60943) }

var fileDescriptor_hub_8be8b914c2a60943 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x71, 0x12, 0xba, 0xf5, 0xd1, 0x8c, 0xcc, 0x42, 0x28, 0x42, 0x1c, 0xa6, 0x08, 0xa1,
	0x89, 0xa1, 0x1e, 0xb6, 0x0b, 0x37, 0x60, 0x99, 0xd1, 0x02, 0x88, 0x44, 0x6e, 0xd1, 0x38, 0x70,
	0x49, 0x16, 0x2b, 0xb5, 0xe8, 0xec, 0x61, 0x3b, 0x42, 0xe2, 0x4f, 0xe4, 0xaf, 0x42, 0xf6, 0x12,
	0xa5, 0xad, 0xd4, 0xaa, 0x37, 0xbf, 0xf7, 0x7e, 0xf9, 0xfc, 0xe5, 0xb3, 0x0d, 0xe3, 0x45, 0x5b,
	0x4d, 0xef, 0x95, 0x34, 0x12, 0xfb, 0x8b, 0xb6, 0x4a, 0xce, 0xe0, 0x29, 0x65, 0x0d, 0xd7, 0x86,
	0x29, 0xca, 0x7e, 0xb7, 0x4c, 0x1b, 0x1c, 0xc3, 0x41, 0xd9, 0x30, 0x61, 0xb2, 0x3a, 0x46, 0x27,
	0xe8, 0x74, 0x4c, 0xfb, 0x32, 0xf9, 0x0c, 0xd1, 0x00, 0xeb, 0x7b, 0x29, 0x34, 0xdb, 0x4e, 0xe3,
	0x97, 0x30, 0xd6, 0x4c, 0x6b, 0x2e, 0x45, 0x56, 0xc7, 0x9e, 0x9b, 0x0d, 0x8d, 0xe4, 0x3d, 0x3c,
	0xa1, 0xac, 0xac, 0xfb, 0x4d, 0xd7, 0x60, 0xb4, 0x01, 0x63, 0x0c, 0x81, 0xe6, 0x7f, 0x99, 0x53,
	0x09, 0xa9, 0x5b, 0x27, 0x3f, 0x61, 0xf2, 0x20, 0xd0, 0x19, 0xe9, 0x19, 0x34, 0x30, 0xb6, 0x57,
	0x97, 0xa6, 0x74, 0xdf, 0x4d, 0xa8, 0x5b, 0xe3, 0x57, 0xe0, 0x33, 0xa5, 0x62, 0xff, 0x04, 0x9d,
	0x1e, 0x9d, 0xe3, 0xa9, 0xcd, 0x23, 0x95, 0x42, 0xb0, 0x5b, 0xc3, 0xa5, 0x20, 0x4a, 0x51, 0x3b,
	0x4e, 0x3e, 0xc0, 0xe4, 0x46, 0x71, 0xc3, 0xf6, 0xf6, 0xb7, 0xb9, 0x4f, 0x92, 0x41, 0xd8, 0x29,
	0xec, 0x30, 0xd8, 0x99, 0xf1, 0x76, 0x9b, 0x79, 0x07, 0xc1, 0xc7, 0xba, 0x56, 0x36, 0x6b, 0xc1,
	0xcc, 0x1f, 0xa9, 0x7e, 0xf5, 0x59, 0x77, 0x25, 0x7e, 0x0e, 0x23, 0x6d, 0x14, 0x17, 0x4d, 0x17,
	0x74, 0x57, 0xbd, 0x99, 0x41, 0xb8, 0xa6, 0x87, 0x47, 0xe0, 0xe5, 0x5f, 0xa2, 0x47, 0xf8, 0x00,
	0x7c, 0x92, 0x7f, 0x8a, 0x10, 0x3e, 0x86, 0xf0, 0xfb, 0x37, 0xf2, 0xa3, 0x20, 0xe9, 0x9c, 0x5c,
	0xd9, 0x96, 0x87, 0x8f, 0x00, 0x66, 0xd7, 0x39, 0x9d, 0xdf, 0xd0, 0x6c, 0x4e, 0x22, 0xdf, 0xd6,
	0xe9, 0xd7, 0x7c, 0x46, 0xae, 0x8a, 0xac, 0x20, 0x51, 0x70, 0xfe, 0x0f, 0x01, 0x0c, 0xaa, 0xf8,
	0x02, 0x0e, 0xfb, 0x5b, 0x81, 0x9f, 0xb9, 0x5f, 0xd8, 0xb8, 0x51, 0x2f, 0x8e, 0xbb, 0xee, 0xca,
	0x69, 0x9d, 0x41, 0x60, 0x6b, 0x1c, 0xad, 0x8c, 0xb6, 0xc2, 0x6f, 0xe1, 0xb1, 0x8b, 0x72, 0x6f,
	0x3a, 0x5d, 0x4a, 0xbd, 0x1f, 0x7d, 0xf9, 0x1a, 0xe2, 0x86, 0x1b, 0xdb, 0xbe, 0x95, 0x77, 0x53,
	0xbd, 0x60, 0xcb, 0x25, 0xbf, 0xd3, 0xdc, 0x82, 0x97, 0x87, 0xd7, 0x6d, 0x55, 0xd8, 0xb7, 0x52,
	0xa0, 0x6a, 0xe4, 0x1e, 0xcd, 0xc5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xbd, 0x54, 0xc9,
	0x41, 0x03, 0x00, 0x00,
}
