// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub.proto

package hub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConnectionErr int32

const (
	ConnectionErr_OK    ConnectionErr = 0
	ConnectionErr_Error ConnectionErr = 1
)

var ConnectionErr_name = map[int32]string{
	0: "OK",
	1: "Error",
}
var ConnectionErr_value = map[string]int32{
	"OK":    0,
	"Error": 1,
}

func (x ConnectionErr) String() string {
	return proto.EnumName(ConnectionErr_name, int32(x))
}
func (ConnectionErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{0}
}

type ReadErr int32

const (
	ReadErr_READ_OK         ReadErr = 0
	ReadErr_EOF             ReadErr = 1
	ReadErr_UNEXPECTEDEOF   ReadErr = 2
	ReadErr_READ_CLOSEDPIPE ReadErr = 3
)

var ReadErr_name = map[int32]string{
	0: "READ_OK",
	1: "EOF",
	2: "UNEXPECTEDEOF",
	3: "READ_CLOSEDPIPE",
}
var ReadErr_value = map[string]int32{
	"READ_OK":         0,
	"EOF":             1,
	"UNEXPECTEDEOF":   2,
	"READ_CLOSEDPIPE": 3,
}

func (x ReadErr) String() string {
	return proto.EnumName(ReadErr_name, int32(x))
}
func (ReadErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{1}
}

type WriteErr int32

const (
	WriteErr_WRITE_OK         WriteErr = 0
	WriteErr_SHORTWRITE       WriteErr = 1
	WriteErr_WRITE_CLOSEDPIPE WriteErr = 2
)

var WriteErr_name = map[int32]string{
	0: "WRITE_OK",
	1: "SHORTWRITE",
	2: "WRITE_CLOSEDPIPE",
}
var WriteErr_value = map[string]int32{
	"WRITE_OK":         0,
	"SHORTWRITE":       1,
	"WRITE_CLOSEDPIPE": 2,
}

func (x WriteErr) String() string {
	return proto.EnumName(WriteErr_name, int32(x))
}
func (WriteErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{2}
}

type RegisterRequest struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{0}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

type RegisterResponse struct {
	AgentId              string        `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	SessionId            string        `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Error                ConnectionErr `protobuf:"varint,3,opt,name=error,proto3,enum=hub.ConnectionErr" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{1}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *RegisterResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *RegisterResponse) GetError() ConnectionErr {
	if m != nil {
		return m.Error
	}
	return ConnectionErr_OK
}

type ReadRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{2}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (dst *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(dst, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ReadRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReadResponse struct {
	Size                 uint32   `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Err                  ReadErr  `protobuf:"varint,3,opt,name=err,proto3,enum=hub.ReadErr" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{3}
}
func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (dst *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(dst, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ReadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ReadResponse) GetErr() ReadErr {
	if m != nil {
		return m.Err
	}
	return ReadErr_READ_OK
}

type WriteRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{4}
}
func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (dst *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(dst, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *WriteRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WriteResponse struct {
	Size                 uint32   `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Err                  WriteErr `protobuf:"varint,2,opt,name=err,proto3,enum=hub.WriteErr" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{5}
}
func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (dst *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(dst, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *WriteResponse) GetErr() WriteErr {
	if m != nil {
		return m.Err
	}
	return WriteErr_WRITE_OK
}

type CloseRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{6}
}
func (m *CloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequest.Unmarshal(m, b)
}
func (m *CloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequest.Marshal(b, m, deterministic)
}
func (dst *CloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequest.Merge(dst, src)
}
func (m *CloseRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRequest.Size(m)
}
func (m *CloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequest proto.InternalMessageInfo

func (m *CloseRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type CloseResponse struct {
	Err                  ConnectionErr `protobuf:"varint,1,opt,name=err,proto3,enum=hub.ConnectionErr" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CloseResponse) Reset()         { *m = CloseResponse{} }
func (m *CloseResponse) String() string { return proto.CompactTextString(m) }
func (*CloseResponse) ProtoMessage()    {}
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{7}
}
func (m *CloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseResponse.Unmarshal(m, b)
}
func (m *CloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseResponse.Marshal(b, m, deterministic)
}
func (dst *CloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseResponse.Merge(dst, src)
}
func (m *CloseResponse) XXX_Size() int {
	return xxx_messageInfo_CloseResponse.Size(m)
}
func (m *CloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseResponse proto.InternalMessageInfo

func (m *CloseResponse) GetErr() ConnectionErr {
	if m != nil {
		return m.Err
	}
	return ConnectionErr_OK
}

type Addr struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	String_              string   `protobuf:"bytes,2,opt,name=string,proto3" json:"string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addr) Reset()         { *m = Addr{} }
func (m *Addr) String() string { return proto.CompactTextString(m) }
func (*Addr) ProtoMessage()    {}
func (*Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_00d89fed6543f948, []int{8}
}
func (m *Addr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addr.Unmarshal(m, b)
}
func (m *Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addr.Marshal(b, m, deterministic)
}
func (dst *Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addr.Merge(dst, src)
}
func (m *Addr) XXX_Size() int {
	return xxx_messageInfo_Addr.Size(m)
}
func (m *Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_Addr.DiscardUnknown(m)
}

var xxx_messageInfo_Addr proto.InternalMessageInfo

func (m *Addr) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Addr) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "hub.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "hub.RegisterResponse")
	proto.RegisterType((*ReadRequest)(nil), "hub.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "hub.ReadResponse")
	proto.RegisterType((*WriteRequest)(nil), "hub.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "hub.WriteResponse")
	proto.RegisterType((*CloseRequest)(nil), "hub.CloseRequest")
	proto.RegisterType((*CloseResponse)(nil), "hub.CloseResponse")
	proto.RegisterType((*Addr)(nil), "hub.Addr")
	proto.RegisterEnum("hub.ConnectionErr", ConnectionErr_name, ConnectionErr_value)
	proto.RegisterEnum("hub.ReadErr", ReadErr_name, ReadErr_value)
	proto.RegisterEnum("hub.WriteErr", WriteErr_name, WriteErr_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectionClient is the client API for Connection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
}

type connectionClient struct {
	cc *grpc.ClientConn
}

func NewConnectionClient(cc *grpc.ClientConn) ConnectionClient {
	return &connectionClient{cc}
}

func (c *connectionClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/hub.Connection/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/hub.Connection/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, "/hub.Connection/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, "/hub.Connection/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServer is the server API for Connection service.
type ConnectionServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
}

func RegisterConnectionServer(s *grpc.Server, srv ConnectionServer) {
	s.RegisterService(&_Connection_serviceDesc, srv)
}

func _Connection_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Connection/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Connection/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Connection/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connection_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Connection/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Connection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hub.Connection",
	HandlerType: (*ConnectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Connection_Register_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Connection_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Connection_Write_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Connection_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub.proto",
}

func init() { proto.RegisterFile("hub.proto", fileDescriptor_hub_00d89fed6543f948) }

var fileDescriptor_hub_00d89fed6543f948 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x18, 0xc5, 0x71, 0xb3, 0xfe, 0xfb, 0x96, 0x6c, 0xe9, 0xc7, 0x40, 0x11, 0x42, 0x30, 0x45, 0x08,
	0x55, 0x1d, 0xea, 0xc5, 0x10, 0x82, 0x2b, 0x60, 0x6b, 0x0d, 0xab, 0x40, 0x34, 0xf2, 0x0a, 0xe3,
	0x0e, 0xb5, 0x8b, 0xd5, 0x46, 0x74, 0xf1, 0xb0, 0x5d, 0x21, 0xf1, 0x98, 0x3c, 0x11, 0xb2, 0xe3,
	0x2c, 0x6d, 0xa5, 0xa1, 0xdd, 0xc5, 0xc7, 0xc7, 0xc7, 0xbf, 0xfa, 0xb8, 0x86, 0xf6, 0x62, 0x35,
	0xeb, 0x5f, 0x4b, 0xa1, 0x05, 0x7a, 0x8b, 0xd5, 0x2c, 0x3e, 0x82, 0x7d, 0xc6, 0xe7, 0x99, 0xd2,
	0x5c, 0x32, 0xfe, 0x6b, 0xc5, 0x95, 0xc6, 0x08, 0x9a, 0xd3, 0x39, 0xcf, 0xf5, 0x28, 0x8d, 0xc8,
	0x21, 0xe9, 0xb6, 0x59, 0x39, 0x8c, 0x35, 0x84, 0x95, 0x59, 0x5d, 0x8b, 0x5c, 0xf1, 0xdb, 0xdd,
	0xf8, 0x18, 0xda, 0x8a, 0x2b, 0x95, 0x89, 0x7c, 0x94, 0x46, 0x35, 0x3b, 0x57, 0x09, 0xd8, 0x85,
	0x3a, 0x97, 0x52, 0xc8, 0xc8, 0x3b, 0x24, 0xdd, 0xbd, 0x63, 0xec, 0x1b, 0xb0, 0x81, 0xc8, 0x73,
	0x7e, 0xa9, 0x33, 0x91, 0x53, 0x29, 0x59, 0x61, 0x88, 0xdf, 0xc1, 0x2e, 0xe3, 0xd3, 0xb4, 0xc4,
	0xdb, 0x88, 0x25, 0xdb, 0xb1, 0x08, 0x3b, 0x2a, 0xfb, 0xc3, 0xed, 0x7e, 0x01, 0xb3, 0xdf, 0xf1,
	0x37, 0xf0, 0x8b, 0x00, 0x87, 0x5c, 0x7a, 0x48, 0xe5, 0x31, 0x5a, 0x3a, 0xd5, 0x53, 0xbb, 0xce,
	0x67, 0xf6, 0x1b, 0x9f, 0x80, 0xc7, 0x65, 0x09, 0xe8, 0x5b, 0x40, 0x93, 0x63, 0xd0, 0xcc, 0x44,
	0xfc, 0x1e, 0xfc, 0x0b, 0x99, 0x69, 0x7e, 0x67, 0xb2, 0xed, 0x1d, 0xe2, 0x21, 0x04, 0x2e, 0xe1,
	0x3f, 0x68, 0x4f, 0x0b, 0x8c, 0x9a, 0xc5, 0x08, 0x2c, 0x86, 0x5d, 0x74, 0xc3, 0xf1, 0x02, 0xfc,
	0xc1, 0x52, 0xa8, 0xbb, 0x71, 0xc4, 0xaf, 0x20, 0x70, 0x6e, 0xb7, 0xe7, 0xb3, 0x22, 0x9f, 0xdc,
	0xda, 0x83, 0xdd, 0xe4, 0x0d, 0xec, 0x9c, 0xa4, 0xa9, 0x34, 0x7d, 0xe7, 0x5c, 0xff, 0x16, 0xf2,
	0x67, 0xd9, 0xb7, 0x1b, 0xe2, 0x43, 0x68, 0x28, 0x2d, 0xb3, 0x7c, 0xee, 0xca, 0x76, 0xa3, 0x5e,
	0x0c, 0xc1, 0x46, 0x1e, 0x36, 0xa0, 0x36, 0xfe, 0x14, 0xde, 0xc3, 0x36, 0xd4, 0xa9, 0x69, 0x38,
	0x24, 0xbd, 0x8f, 0xd0, 0x74, 0x47, 0x8b, 0xbb, 0xd0, 0x64, 0xf4, 0x64, 0xf8, 0xc3, 0x5a, 0x9a,
	0xe0, 0xd1, 0xf1, 0x87, 0x90, 0x60, 0x07, 0x82, 0xaf, 0x5f, 0xe8, 0xf7, 0x84, 0x0e, 0x26, 0x74,
	0x68, 0xa4, 0x1a, 0xde, 0x87, 0x7d, 0x6b, 0x1c, 0x7c, 0x1e, 0x9f, 0xd3, 0x61, 0x32, 0x4a, 0x68,
	0xe8, 0xf5, 0xde, 0x42, 0xab, 0x3c, 0x1c, 0xf4, 0xa1, 0x75, 0xc1, 0x46, 0x13, 0x5a, 0x44, 0xed,
	0x01, 0x9c, 0x9f, 0x8d, 0xd9, 0xc4, 0x4a, 0x21, 0xc1, 0x03, 0x08, 0x8b, 0xd9, 0xb5, 0xf5, 0xb5,
	0xe3, 0xbf, 0x04, 0xa0, 0xa2, 0xc5, 0xd7, 0xd0, 0x2a, 0x6f, 0x3c, 0x1e, 0xb8, 0x1b, 0xb0, 0xf1,
	0x6f, 0x79, 0xf4, 0x60, 0x4b, 0x75, 0x87, 0x7a, 0x04, 0x3b, 0xe6, 0x07, 0x61, 0x78, 0x73, 0x6d,
	0xca, 0x05, 0x9d, 0x35, 0xc5, 0x99, 0xfb, 0x50, 0xb7, 0xd0, 0xd8, 0xa9, 0xda, 0x2d, 0xed, 0xb8,
	0x2e, 0x55, 0x7e, 0x5b, 0xa1, 0xf3, 0xaf, 0x97, 0xef, 0xfc, 0x1b, 0x0d, 0x9f, 0x3e, 0x87, 0x68,
	0x9e, 0x69, 0xa3, 0x5f, 0x8a, 0xab, 0xbe, 0x5a, 0xf0, 0xe5, 0x32, 0xbb, 0x52, 0x99, 0x71, 0x9e,
	0xb6, 0xce, 0x56, 0xb3, 0xc4, 0xbc, 0x07, 0x09, 0x99, 0x35, 0xec, 0xc3, 0xf0, 0xf2, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x3d, 0x2c, 0x81, 0x6e, 0x25, 0x04, 0x00, 0x00,
}
