// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub.proto

package hub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_UNKNOWN Status = 0
	Status_OK      Status = 1
	Status_INVALID Status = 2
	Status_FAILED  Status = 3
)

var Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "INVALID",
	3: "FAILED",
}
var Status_value = map[string]int32{
	"UNKNOWN": 0,
	"OK":      1,
	"INVALID": 2,
	"FAILED":  3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hub_1789f61e87b4e114, []int{0}
}

type WinsizeRequest struct {
	Rows                 uint32   `protobuf:"varint,1,opt,name=rows" json:"rows,omitempty"`
	Cols                 uint32   `protobuf:"varint,2,opt,name=cols" json:"cols,omitempty"`
	X                    uint32   `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,4,opt,name=y" json:"y,omitempty"`
	SessionId            uint64   `protobuf:"varint,5,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WinsizeRequest) Reset()         { *m = WinsizeRequest{} }
func (m *WinsizeRequest) String() string { return proto.CompactTextString(m) }
func (*WinsizeRequest) ProtoMessage()    {}
func (*WinsizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_1789f61e87b4e114, []int{0}
}
func (m *WinsizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WinsizeRequest.Unmarshal(m, b)
}
func (m *WinsizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WinsizeRequest.Marshal(b, m, deterministic)
}
func (dst *WinsizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinsizeRequest.Merge(dst, src)
}
func (m *WinsizeRequest) XXX_Size() int {
	return xxx_messageInfo_WinsizeRequest.Size(m)
}
func (m *WinsizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WinsizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WinsizeRequest proto.InternalMessageInfo

func (m *WinsizeRequest) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *WinsizeRequest) GetCols() uint32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func (m *WinsizeRequest) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *WinsizeRequest) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *WinsizeRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type WinsizeResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WinsizeResponse) Reset()         { *m = WinsizeResponse{} }
func (m *WinsizeResponse) String() string { return proto.CompactTextString(m) }
func (*WinsizeResponse) ProtoMessage()    {}
func (*WinsizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hub_1789f61e87b4e114, []int{1}
}
func (m *WinsizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WinsizeResponse.Unmarshal(m, b)
}
func (m *WinsizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WinsizeResponse.Marshal(b, m, deterministic)
}
func (dst *WinsizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinsizeResponse.Merge(dst, src)
}
func (m *WinsizeResponse) XXX_Size() int {
	return xxx_messageInfo_WinsizeResponse.Size(m)
}
func (m *WinsizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WinsizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WinsizeResponse proto.InternalMessageInfo

func (m *WinsizeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*WinsizeRequest)(nil), "hub.WinsizeRequest")
	proto.RegisterType((*WinsizeResponse)(nil), "hub.WinsizeResponse")
	proto.RegisterEnum("hub.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TerminalClient is the client API for Terminal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TerminalClient interface {
	Resize(ctx context.Context, in *WinsizeRequest, opts ...grpc.CallOption) (*WinsizeResponse, error)
}

type terminalClient struct {
	cc *grpc.ClientConn
}

func NewTerminalClient(cc *grpc.ClientConn) TerminalClient {
	return &terminalClient{cc}
}

func (c *terminalClient) Resize(ctx context.Context, in *WinsizeRequest, opts ...grpc.CallOption) (*WinsizeResponse, error) {
	out := new(WinsizeResponse)
	err := c.cc.Invoke(ctx, "/hub.Terminal/Resize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerminalServer is the server API for Terminal service.
type TerminalServer interface {
	Resize(context.Context, *WinsizeRequest) (*WinsizeResponse, error)
}

func RegisterTerminalServer(s *grpc.Server, srv TerminalServer) {
	s.RegisterService(&_Terminal_serviceDesc, srv)
}

func _Terminal_Resize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WinsizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServer).Resize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.Terminal/Resize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServer).Resize(ctx, req.(*WinsizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Terminal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hub.Terminal",
	HandlerType: (*TerminalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resize",
			Handler:    _Terminal_Resize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub.proto",
}

func init() { proto.RegisterFile("hub.proto", fileDescriptor_hub_1789f61e87b4e114) }

var fileDescriptor_hub_1789f61e87b4e114 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4b, 0xc3, 0x40,
	0x14, 0xc4, 0xdd, 0x24, 0xc6, 0xe6, 0xf9, 0x15, 0x9e, 0x22, 0x8b, 0x20, 0x94, 0x1e, 0xa4, 0x7a,
	0xc8, 0xc1, 0x82, 0x57, 0x69, 0xa9, 0x62, 0x68, 0x49, 0x4b, 0xfc, 0xe8, 0x51, 0x9a, 0x76, 0x31,
	0x0b, 0x49, 0xb6, 0xe6, 0x65, 0xb1, 0xf5, 0xaf, 0x97, 0x4d, 0xaa, 0xd0, 0xdb, 0xcc, 0x6f, 0x17,
	0xe6, 0xcd, 0x80, 0x97, 0xea, 0x24, 0x58, 0x95, 0xaa, 0x52, 0x68, 0xa7, 0x3a, 0xe9, 0x10, 0x9c,
	0xcc, 0x64, 0x41, 0xf2, 0x47, 0xc4, 0xe2, 0x4b, 0x0b, 0xaa, 0x10, 0xc1, 0x29, 0xd5, 0x37, 0x71,
	0xd6, 0x66, 0xdd, 0xe3, 0xb8, 0xd6, 0x86, 0x2d, 0x54, 0x46, 0xdc, 0x6a, 0x98, 0xd1, 0x78, 0x04,
	0x6c, 0xcd, 0xed, 0x1a, 0xb0, 0xb5, 0x71, 0x1b, 0xee, 0x34, 0x6e, 0x83, 0x57, 0x00, 0x24, 0x88,
	0xa4, 0x2a, 0x3e, 0xe4, 0x92, 0xef, 0xb7, 0x59, 0xd7, 0x89, 0xbd, 0x2d, 0x09, 0x97, 0x9d, 0x1b,
	0x38, 0xfd, 0x0f, 0xa5, 0x95, 0x2a, 0x48, 0xe0, 0x05, 0xb8, 0x2f, 0xd5, 0xbc, 0xd2, 0x4d, 0xae,
	0x17, 0x6f, 0xdd, 0xed, 0xfd, 0x1f, 0xc7, 0x43, 0x38, 0x78, 0x8b, 0x46, 0xd1, 0x64, 0x16, 0xf9,
	0x7b, 0xe8, 0x82, 0x35, 0x19, 0xf9, 0xcc, 0xc0, 0x30, 0x7a, 0xef, 0x8f, 0xc3, 0xa1, 0x6f, 0x21,
	0x80, 0xfb, 0xd4, 0x0f, 0xc7, 0x8f, 0x43, 0xdf, 0xbe, 0x7b, 0x80, 0xd6, 0xab, 0x28, 0x73, 0x59,
	0xcc, 0x33, 0xec, 0x81, 0x1b, 0x0b, 0x93, 0x86, 0x67, 0x81, 0xa9, 0xbf, 0x5b, 0xf8, 0xf2, 0x7c,
	0x17, 0x36, 0x07, 0x0d, 0xae, 0x81, 0x7f, 0xca, 0xca, 0xbc, 0x2c, 0x54, 0x1e, 0x50, 0x2a, 0xb2,
	0x4c, 0xe6, 0x24, 0xcd, 0xdf, 0x41, 0xeb, 0x59, 0x27, 0x53, 0xb3, 0xe1, 0x94, 0x25, 0x6e, 0x3d,
	0x66, 0xef, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x08, 0xac, 0x29, 0x59, 0x01, 0x00, 0x00,
}
